### ISSUE TITLE
Action Links in sortable table wont work

### ISSUE THREAD

**Issue by walerii** [creativetimofficial/ct-argon-dashboard-pro-laravel#20]
# Prerequisites

I am using the latest Version of the dashboard and was able to reconstruct the issue even in your documentation.
Im using a sortable list and i want to use the action links, but they wont redirect to the url. If you try "open in new tab" it will work, if you try the same on a normal table action link, it will also work. So there has to be a problem between the list.js and sortable table that blocks the action links

[screenshot ](https://gyazo.com/f621f5329b1cf8815347a2438a818b58)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. open https://argon-dashboard-pro-laravel.creative-tim.com/docs/components/tables.html
2. inspect table and place some working url in one of the action links
3. click the action link, it will work.
4. open https://argon-dashboard-pro-laravel.creative-tim.com/docs/plugins/list-js.html
5. repeat steps 2 and 3, it wont work.

im using Google Chrome latest version and tested it on your documentation

@rarestoma

**Comment by walerii** [comment]
The same issue seems to apply to the pagination links also. It works on normal table, but not on sortable

**Comment by rarestoma** [comment]
Hi @walerii,

Thank you for working with our products and for pointing us this issue.

It seems to be a problem with list.js, I tried a few things but I didn't find yet a thing to work. I will still try and make some test to see how can we make it work.

Thank you,
Rares

**Comment by walerii** [comment]
Hi @rarestoma,

Thanks for your answer. I now switched to datatables, and it works like a charm.

**Comment by teamupdivision** [comment]
Glad that your problem was solved!

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).

**Comment by jfrydendal** [comment]
Hi Tim,

I think the problem still exists. 

Go to https://argon-dashboard-pro-laravel.creative-tim.com/sortable and click anywhere in the table. You will get this error:
"Uncaught TypeError: Cannot read property 'nodeName' of undefined"
 In your browser developer console.

I hope this is something that can get resolved

**Comment by teamupdivision** [comment]
Hi @Jakoffe, 

Thanks for reporting this issue and for using Creative Tim products.

We've pushed a fix to this problem.
Please download again the product from the downloads section in the Creative Tim website.  

If there is anything else we can help with, please let me know. 

All the best
